### ISSUE TITLE
TODO myCRAFTs

### ISSUE THREAD

**Issue by mjsisley** [mjsisley/myCRAFT#1]
* [ ] Base setup
* [ ] Basic Redux setup
* [ ] RxJS and redux-observable setup
* [ ] Reselect setup

Lower priority:
* [ ] Node Services setup
* [ ] Code splitting setup (dynamic imports)
* [ ] Apollo/Graphcool setup
* [ ] React Native setup (if possible)
* [ ] Firebase setup
